name: PUMLE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.4
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.8.0
  - ipykernel=6.29.5
  - jupyterlab=4.0.6
  - pandas=2.1.1
  - pip=24.2
  - pykan=0.2.8
  - torch=2.2.2
  - tqdm=4.66.2
  - scikit_learn=1.1.3
  - pip:
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - traitlets==5.14.3
